dist: xenial
language: scala
sudo: required

matrix:
  include:
  - stage: test
    env: CI_SCRIPT="mill LaTomate.test"
    jdk: openjdk11
    
script:
  - sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/mill/releases/download/0.3.5/0.3.5) > /usr/local/bin/mill && chmod +x /usr/local/bin/mill'
  - "$CI_SCRIPT"

